# Copied the default nginx config from alpine
server {
        listen 80;
        listen [::]:80;

        # Not everything is a 404
        location / {
                root /var/www/website;
                index index.html;
        }

        # You may need this to prevent return 404 recursion.
        location = /404.html {
                internal;
        }
}