apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ghcr.io/paul-is-online/argo-testing:sha256-038c66a94ea7dd16e5a0d340b6d8a7dac1d14c9f12ed72c86e4c2793d13d1d38
        ports:
        - containerPort: 80